version: "3.7"
services:
    app:
        build:
            args:
                user: lns
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: lns
        container_name: lns-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - lns

    db:
        image: mysql:8.0
        container_name: lns-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - '3307:3306'
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - lns

    nginx:
        image: nginx:alpine
        container_name: lns-nginx
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - lns
    redis:
        image: redis:6.2
        container_name: lns-redis
        ports:
            - "6382:6379"
        networks:
            - lns

networks:
    lns:
        driver: bridge
